name: Build and Release Binary

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build and Release for ${{ matrix.arch }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build binary for ${{ matrix.arch }}
        run: |
          VERSION=${GITHUB_REF_NAME}
          docker run --rm \
            --platform linux/${{ matrix.arch }} \
            -v ${{ github.workspace }}:/app \
            -w /app/with-login \
            ubuntu:20.04 bash -c "
              apt update &&
              DEBIAN_FRONTEND=noninteractive apt install -y python3 python3-pip python3-venv curl build-essential zip &&
              python3 -m pip install --upgrade pip &&
              pip3 install pyinstaller &&
              pip3 install -r requirements.txt &&
              sed -i 's/VERSION = \"dev\"/VERSION = \"${VERSION}\"/g' main.py &&
              pyinstaller --onefile \
                --add-data 'templates:templates' \
                --add-data 'static:static' \
                main.py &&
              mv dist/main dist/mirror-manager-${{ matrix.arch }} &&
              cp ../README.md dist/ &&
              cd dist && zip mirror-manager-${{ matrix.arch }}.zip mirror-manager-${{ matrix.arch }} README.md
            "

      - name: Upload release asset (.zip) for ${{ matrix.arch }}
        uses: softprops/action-gh-release@v2
        with:
          files: with-login/dist/mirror-manager-${{ matrix.arch }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
