name: Build and Release Binary

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build Binary with Ubuntu 20.04 Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build binary in Ubuntu 20.04 container
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app/with-login ubuntu:20.04 bash -c "
            apt update &&
            DEBIAN_FRONTEND=noninteractive apt install -y python3 python3-pip python3-venv curl build-essential &&
            python3 -m pip install --upgrade pip &&
            pip3 install pyinstaller &&
            pip3 install -r requirements.txt &&
            pyinstaller --onefile \
              --add-data 'templates:templates' \
              --add-data 'static:static' \
              main.py &&
            mv dist/main dist/py-mirror-manager
          "

      - name: Upload release binary
        uses: softprops/action-gh-release@v2
        with:
          files: with-login/dist/py-mirror-manager
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
